apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
kind: ControllerManagerConfig
health:
  healthProbeBindAddress: :8086
metrics:
  bindAddress: 127.0.0.1:8085
webhook:
  port: 9443
leaderElection:
  leaderElect: true
  resourceName: 0cd3be86.onprem.local
