# permissions for end users to view charts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: chart-viewer-role
rules:
- apiGroups:
  - app.onprem.local
  resources:
  - charts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - app.onprem.local
  resources:
  - charts/status
  verbs:
  - get
