
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - app.onprem.local
  resources:
  - charts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.onprem.local
  resources:
  - charts/finalizers
  verbs:
  - update
- apiGroups:
  - app.onprem.local
  resources:
  - charts/status
  verbs:
  - get
  - patch
  - update
